version: '3.9'

services:
  redis:
    container_name: yahoo-scraper-redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/data

  app:
    container_name: yahoo-scraper
    image: ghcr.io/zsoltgombocz/yahoo-scraper:latest
    ports:
      - 3006:3000
    volumes:
      - public:/app/public
    environment:
      FINVIZ_BASE_URL: 'https://finviz.com/screener.ashx?v=111&f=cap_smallover&o=company'
      YAHOO_FINANCE_URL: 'https://finance.yahoo.com/quote'
      REDIS_URL: redis://redis:6379
      NODE_ENV: 'production'
      APP_PORT: 3000
    depends_on:
      - redis

volumes:
  redis: {}
  public: {}

